// <auto-generated />
using DotNetQ3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetQ3.Migrations
{
    [DbContext(typeof(ITIContext))]
    [Migration("20240720070119_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetQ3.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerName = "Ahemd",
                            Name = "SD"
                        },
                        new
                        {
                            Id = 2,
                            ManagerName = "Moohamed",
                            Name = "Open Sourse"
                        },
                        new
                        {
                            Id = 3,
                            ManagerName = "Marwa",
                            Name = "AI"
                        });
                });

            modelBuilder.Entity("DotNetQ3.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeptartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeptartmentId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "alex",
                            DeptartmentId = 1,
                            ImageUrl = "1.png",
                            JobTitle = "BackEnd Developer",
                            Name = "Yossef",
                            Salary = 2000
                        },
                        new
                        {
                            Id = 2,
                            Address = "alex",
                            DeptartmentId = 2,
                            ImageUrl = "1.png",
                            JobTitle = "BackEnd Developer",
                            Name = "Ahmed Kamel",
                            Salary = 2000
                        },
                        new
                        {
                            Id = 3,
                            Address = "alex",
                            DeptartmentId = 3,
                            ImageUrl = "1.png",
                            JobTitle = "BackEnd Developer",
                            Name = "Mohamed younes",
                            Salary = 2000
                        });
                });

            modelBuilder.Entity("DotNetQ3.Models.Employee", b =>
                {
                    b.HasOne("DotNetQ3.Models.Department", "Department")
                        .WithMany("Emps")
                        .HasForeignKey("DeptartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DotNetQ3.Models.Department", b =>
                {
                    b.Navigation("Emps");
                });
#pragma warning restore 612, 618
        }
    }
}
